//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouse1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IDProduct { get; set; }
        public string NameProduct { get; set; }
        public string Color { get; set; }
        public int Price { get; set; }
        public int Stok { get; set; }
        public int IDCategory { get; set; }
        public int IDWareHouse { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
