//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouse1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouse
    {
        public WareHouse()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string WareHouse1 { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
